# Generated by Django 4.0.3 on 2022-03-28 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.IntegerField(default=0, max_length=10)),
                ('name_customer', models.CharField(default='', max_length=100)),
                ('password', models.CharField(default='', max_length=20)),
                ('date_of_birth', models.CharField(default='', max_length=10)),
            ],
        ),
    ]
