# Generated by Django 4.0.3 on 2022-05-16 13:31

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('phone_number', models.CharField(default='', max_length=10, primary_key=True, serialize=False)),
                ('name_customer', models.CharField(default='', max_length=100)),
                ('date_of_birth', models.CharField(default='', max_length=10)),
                ('gt', models.BooleanField(default=True)),
                ('register_time', models.DateTimeField(auto_now=True, null=True)),
                ('last_login', models.DateTimeField(auto_now=True, null=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
