# Generated by Django 4.0.3 on 2022-04-04 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_customer_email_customer_customer_gt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='email_customer',
        ),
    ]
