# Generated by Django 4.0.3 on 2022-04-04 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_remove_customer_email_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(default='', max_length=10, primary_key=True, serialize=False),
        ),
    ]
