# Generated by Django 4.0.3 on 2022-03-28 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='short_address',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
