# Generated by Django 4.0.3 on 2022-04-04 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_short_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='land_area',
            new_name='area',
        ),
        migrations.RemoveField(
            model_name='product',
            name='classify',
        ),
        migrations.RemoveField(
            model_name='product',
            name='short_address',
        ),
        migrations.AddField(
            model_name='product',
            name='floors',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='to_center',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='product',
            name='location_house',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
