# Generated by Django 4.0.3 on 2022-05-16 13:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Predict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255)),
                ('area', models.FloatField(default=0.0)),
                ('address', models.CharField(default='', max_length=255)),
                ('location_house', models.IntegerField(default=0)),
                ('floors', models.IntegerField(default=0)),
                ('to_center', models.FloatField(default=0.0)),
                ('price_predict', models.IntegerField(default=0)),
                ('time', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
