# Generated by Django 4.0.3 on 2022-05-16 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='predict',
            old_name='address',
            new_name='email',
        ),
    ]
