# Generated by Django 4.0.3 on 2022-05-16 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0002_rename_address_predict_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predict',
            name='title',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
