# Generated by Django 4.0.3 on 2022-05-20 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0003_alter_predict_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('parameter_id', models.CharField(default='', max_length=255, primary_key=True, serialize=False)),
                ('paramater_list', models.CharField(default='', max_length=255)),
                ('paramater_decriptions', models.TextField(default='')),
                ('time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
