# Generated by Django 4.0.3 on 2022-05-23 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0004_parameter'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Parameter',
            new_name='Parameterr',
        ),
    ]
