# Generated by Django 4.0.3 on 2022-05-20 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0004_parameter'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='paramater_using',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
