# Generated by Django 4.0.3 on 2022-05-23 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0005_rename_parameter_parameterr'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Parameterr',
        ),
    ]
