# Generated by Django 4.0.3 on 2022-05-20 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0005_parameter_paramater_using'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='paramater_using',
            field=models.IntegerField(default=0),
        ),
    ]
