# Generated by Django 4.0.3 on 2022-05-20 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0006_alter_parameter_paramater_using'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parameter',
            old_name='paramater_decriptions',
            new_name='parameter_descriptions',
        ),
        migrations.RenameField(
            model_name='parameter',
            old_name='paramater_list',
            new_name='parameter_list',
        ),
        migrations.RenameField(
            model_name='parameter',
            old_name='paramater_using',
            new_name='parameter_using',
        ),
    ]
